<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>6748fff7ba091ba15e8b1948</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-04-06 10:51:41</createtime><buildsignature>Local.Unknown.Unknown.1.47.49.1020-1.200.000.373.Release</buildsignature><categoryid>outfit_change_element.py:39</categoryid><desyncid>6748fff7ba091ba15e8b1948</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'XevtOutfitChangeForReason' object has no attribute 'xevt_outfit_change')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 281, in _do&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 694, in _build_elements&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 225, in build_outcome_actions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 241, in build_basic_extra_outcomes&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\tunable.py", line 523, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\outfits\outfit_change_element.py", line 143, in __init__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\outfits\outfit_change_element.py", line 39, in get_xevt_outfit&#13;&#10;AttributeError: 'XevtOutfitChangeForReason' object has no attribute 'xevt_outfit_change'&#13;&#10;rtim=0</desyncdata></report>
</root>